### ISSUE TITLE
Pokemon Game Editor

### ISSUE THREAD

**Issue by HexadecimalMantis** [Gamer2020/PokemonGameEditor#3]
When I open the Ability, Move, and Pokemon editor with pokemon game editor, it crashes.

**Comment by Gamer2020** [comment]
Can you please provide more information? What game were you using? How did it crash?

**Comment by HexadecimalMantis** [comment]
I was using pokemon ruby and it crashed from an unhandald exception.

**Comment by Gamer2020** [comment]
The most likely problem is that their are offsets missing from the ini. People should be using Fire Red or Emerald so I don't usually add all the offsets for Ruby. To get it to work simply add the offsets to the ini. Alternatively consider using Fire Red or Emerald because they contain more features.

**Comment by HexadecimalMantis** [comment]
thanks
