### ISSUE TITLE
Error Selecting Index

### ISSUE THREAD

**Issue by Joexv** [Gamer2020/PokemonGameEditor#5]
Using expanded evolution methods that require a species or move argument the program throws out a Selected Index Error.

The arguments listed in the ini are attack and species

**Comment by Gamer2020** [comment]
Dear SIr or Madam,

I apologize that an error is occurring for you. Unfortunately I may require some more information in order to resolve this issue. If possible please send me a copy or your ini and patch of your ROM. For confidentiality reasons you may email me at lostatlife2020@hotmail.com, I will then be able to run the debugger and figure out exactly what it going on.

- Gamer2020

P.S. I apologize for the late replay but I was out of the country and unable to access the internet.

**Comment by Joexv** [comment]
Email with ROM and ini have been sent

**Comment by Gamer2020** [comment]
Issue resolved trough email. Fix synced.
